services:

  postgres:
    image: postgres:17
    container_name: biblioteca-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${DB_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    build:
      context: ./backend

    container_name: biblioteca-backend
    restart: unless-stopped

    environment:
      DB_URI: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DRIVER: org.postgresql.Driver

    ports:
      - "${BACKEND_PORT}:8080"

    depends_on:
      - postgres


  frontend:
    build:
      context: ./frontend

    container_name: biblioteca-frontend
    restart: unless-stopped

    ports:
      - "3000:80"

    depends_on:
      - backend


volumes:
  postgres_data: